### PR TITLE
Allow css file pattern customisation

### PR DESCRIPTION
**Pull request by vKongv**
This is to allow user to pass in `test` option to specifies the file they want to customise.

### CODE REVIEW

**Comment by vKongv** [comment]
@satazor I was trying to customise the `css` path for css module in webpack but couldn't find any so I submitted this PR to allow `test` path customisation

**Comment by vKongv** [comment]
Reason why is because I want to introduce css modules to an existing project but didn't want to refactor the other `css` code yet.

**Comment by satazor** [comment]
@vKongv couldn't you use the `include` option to do the same thing?

**Comment by vKongv** [comment]
@satazor So it will be include `src/**/*.module.css`?

**Comment by vKongv** [comment]
But I think the rule will override the default one right because it will match `test: /\.css$/` first rule first so it will skip the second rule which is the default rule from CRA.

**Comment by satazor** [comment]
Ok I understand it now, could you please document the option in the README?

**Comment by vKongv** [comment]
@satazor Added :D

**Review by satazor — CHANGES_REQUESTED** [review]
Could you put the test option before include everywhere (code and readme)? Then it’s good to be merged.

**Comment by vKongv** [comment]
@hugomrdias Moved.

**Review by satazor — APPROVED** [review]

**Comment by satazor** [comment]
I will release a new version later tonight. Ping me if I don’t.

**Comment by vKongv** [comment]
@satazor Just a reminder on the release :D

**Comment by satazor** [comment]
Released 🎉

Sorry for the delay, I'm currently in vacations.

**Comment by vKongv** [comment]
Thanks man! No worries, have fun in your vacation :D

**Comment by vKongv** [comment]
Thanks man! No worries and have fun in your vacation :D

**Pull request merged**
